### ISSUE TITLE
Allow to silence the calls instead of blocking 

### ISSUE THREAD

**Issue by adeekshith** [x13a/Silence#111]
Would be great if we have a switch to silence the call instead of blocking it

**Comment by adeekshith** [comment]
I can make a PR with this feature if fine with you.

Screenshot with proposed option
![silence](https://user-images.githubusercontent.com/2568945/159579861-ea12b901-1331-42e9-accc-f287d4359e18.png)

**Comment by Ilithy** [comment]
Hello, if I can ask a question, what is the difference with the silent mode of any phone? (just mute) Do you plan to add floating notification sub-options with actions such as take the call, send to voicemail etc...? Or something else? Otherwise it complicates the silencing, and its deactivation (compared to just lowering the sound to zero)

**Comment by x13a** [comment]
@adeekshith no problems, but this functionality has to be added to the general settings (long press on the main toggle). 

@Ilithy `CallScreeningService` API has some options for response, like: _disallow_, _reject_ and _silence_. The app uses _reject_. You can read about it here: https://developer.android.com/reference/android/telecom/CallScreeningService.CallResponse.Builder

**Comment by x13a** [comment]
Done
